stages:
  - test
  - release

variables:
  LANG: en_US.UTF-8
  BUILD_IMAGES_PROJECT: kiwi3/kiwi-ci-containers
  FEDORA_BUILD: buildenv-fedora

code_style:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  stage: test
  script:
    - tox -e check
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .tox/3

unit_py36:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  stage: test
  script:
    - export PYTHON=python3.6
    - tox -e unit_py3_6 "-n $(nproc)"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .tox/3.6

unit_py38:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  stage: test
  script:
    - export PYTHON=python3.8
    - tox -e unit_py3_8 "-n $(nproc)"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .tox/3.8

pypi_upload:
  stage: release
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  only:
    - tags
  script:
    - base64 --decode "$PYPI_CONFIG" > .pypirc
    - export PYTHON=python3.6
    - tox -e release
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .tox/3.6
